import { chromium } from 'playwright';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync, spawn } from 'node:child_process';
import path from 'node:path';

const OUT=path.resolve(process.env.PLAN_QA_OUTPUT||'/tmp/yumao-plan-real-e2e');await mkdir(OUT,{recursive:false});
const repo=path.resolve(new URL('..',import.meta.url).pathname,'..');const port=Number(process.env.PLAN_QA_BACKEND_PORT||5518);const vitePort=Number(process.env.PLAN_QA_VITE_PORT||5517);const origin=`http://127.0.0.1:${vitePort}`;
const python=process.env.PLAN_QA_PYTHON||execFileSync('conda',['run','-n','test','python','-c','import sys; print(sys.executable)'],{encoding:'utf8'}).trim();
const dbServer=spawn(python,['-m','backend.tests.plan_browser_server','--output',OUT,'--origin',origin,'--port',String(port)],{cwd:repo,stdio:['ignore','pipe','inherit']});
let serverLine='';dbServer.stdout.on('data',chunk=>{serverLine+=chunk.toString();});for(let i=0;i<80&&!serverLine.includes('"origin"');i++)await new Promise(r=>setTimeout(r,100));if(!serverLine.includes('"origin"'))throw new Error('synthetic Flask server did not start');
const vite=spawn('npm',['run','dev','--','--config','e2e/plans-real.vite.config.mjs'],{cwd:path.join(repo,'frontend'),env:{...process.env,PLAN_QA_BACKEND:`http://127.0.0.1:${port}`,PLAN_QA_PORT:String(vitePort),PLAN_QA_CACHE:path.join(OUT,'vite-cache')},stdio:['ignore','pipe','inherit']});await new Promise(r=>setTimeout(r,1800));
const browser=await chromium.launch({headless:true});const report={screenshots:[],checks:[],network:[],errors:[]};
function check(name,passed,evidence={}){report.checks.push({name,status:passed?'PASS':'FAIL',evidence});if(!passed)throw new Error(name);}
async function context(name,width,height){const ctx=await browser.newContext({viewport:{width,height},timezoneId:'Asia/Shanghai'});const page=await ctx.newPage();page.on('pageerror',e=>report.errors.push({name,type:'pageerror',message:e.message}));page.on('console',m=>{if(['error','warning'].includes(m.type()))report.errors.push({name,type:m.type(),message:m.text()});});page.on('request',r=>{if(new URL(r.url()).origin!==origin)report.network.push({name,url:r.url()});});return {ctx,page,name};}
async function shot(item,tag){const file=path.join(OUT,`${tag}.jpg`);await item.page.screenshot({path:file,fullPage:true});report.screenshots.push(file);}
async function login(page,user){await page.goto(`${origin}/login`);await page.getByLabel('用户名').fill(user);await page.getByLabel('密码').fill('Synthetic-only-password-42');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('link',{name:'预约计划',exact:true}).click();await page.getByRole('heading',{name:'我的预约计划'}).waitFor();}
try {
 const a=await context('desktop-A',1440,900);await login(a.page,'plan_user_a');await a.page.getByText('还没有预约计划').waitFor({state:'visible',timeoutMs:10000});check('A starts empty',await a.page.getByText('还没有预约计划').count()===1);await a.page.getByRole('button',{name:'新建预约计划'}).click();await a.page.getByLabel('目标预约日期').fill('2026-10-20');await a.page.getByLabel('场馆名称或描述（人工偏好）').fill('Playwright真实人工场馆');await a.page.getByLabel('场地偏好（人工输入，每行一项）').fill('6号场优先\n5号场备选');await a.page.getByLabel(/价格上限/).fill('29.90');await a.page.getByRole('button',{name:'保存预约意向'}).click();await a.page.getByText(/已保存预约意向 · 版本 1/).waitFor({state:'visible',timeoutMs:10000});check('A creates',true);check('distant date visible',await a.page.getByText('当前不可查询').count()>=1);await shot(a,'desktop-created');await a.page.reload();await a.page.getByText('Playwright真实人工场馆').waitFor({state:'visible',timeoutMs:10000});check('refresh persists',true);await a.page.getByRole('button',{name:'编辑计划'}).click();await a.page.getByLabel('场馆名称或描述（人工偏好）').fill('Playwright编辑后场馆');await a.page.getByRole('button',{name:'保存预约意向'}).click();await a.page.getByText(/已保存预约意向 · 版本 2/).waitFor({state:'visible',timeoutMs:10000});check('A version increments',true);await a.page.getByRole('button',{name:'版本历史'}).click();await a.page.getByRole('heading',{name:'版本历史'}).waitFor({state:'visible'});check('history visible',true);await shot(a,'desktop-history');
 const phone=await context('phone-B',390,844);await login(phone.page,'plan_user_b');await phone.page.getByText('还没有预约计划').waitFor({state:'visible',timeoutMs:10000});check('B cannot see A plan',await phone.page.getByText('Playwright编辑后场馆').count()===0);check('phone no horizontal overflow',await phone.page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await shot(phone,'phone-empty');
 const narrow=await context('narrow-320',320,700);await login(narrow.page,'plan_user_b');await narrow.page.getByText('还没有预约计划').waitFor({state:'visible',timeoutMs:10000});check('320px no horizontal overflow',await narrow.page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await narrow.ctx.close();
 await a.ctx.close();await phone.ctx.close();
} finally {await browser.close();vite.kill('SIGTERM');dbServer.kill('SIGTERM');await writeFile(path.join(OUT,'results.json'),JSON.stringify(report,null,2));}
console.log(JSON.stringify({output:OUT,checks:report.checks.length,passed:report.checks.filter(x=>x.status==='PASS').length,failed:report.checks.filter(x=>x.status==='FAIL').length,network:report.network.length,errors:report.errors.length}));
