import { flushPromises, mount, enableAutoUnmount } from '@vue/test-utils';
import { reactive } from 'vue';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { context, intent, plan, windowState } from '../components/plans/testFixtures.js';

enableAutoUnmount(afterEach);
const clone=(v)=>structuredClone(v);
function apiFixture(overrides={}) { return {list:vi.fn(async()=>({plans:[plan()]})),options:vi.fn(async()=>({catalog_status:'not_configured',venues:[],context:clone(context)})),window:vi.fn(async()=>clone(windowState)),get:vi.fn(async()=>({plan:plan(2,{venue_preference:'另一个窗口保存'})})),create:vi.fn(async(value)=>({plan:plan(1,value)})),update:vi.fn(async(_id,_version,value)=>({plan:plan(2,value)})),revisions:vi.fn(async()=>({revisions:[{...plan(2),revision_number:2,revision_id:'revision-2'},{...plan(),revision_number:1,revision_id:'revision-1'}]})),...overrides}; }
async function mountView(api=apiFixture()) { const m=await import('./PlansView.vue').catch(()=>null);expect(m).not.toBeNull();const session=reactive({status:'authenticated',user:{user_id:'a',username:'Alice'},csrfToken:'csrf-a',refresh:vi.fn()});const wrapper=mount(m.default,{global:{provide:{planApi:api,sessionStore:session}}});await flushPromises();return {wrapper,api,session}; }
async function newDraft(wrapper) {await wrapper.get('[data-testid="new-plan"]').trigger('click');await flushPromises();await wrapper.get('[name="venue_preference"]').setValue('周末人工意向');await wrapper.get('[name="court_preferences"]').setValue('6号场\n5号场');await wrapper.get('[name="target_date"]').setValue('2026-10-20');await flushPromises();}
async function edit(wrapper) { await wrapper.get('[data-testid="edit-plan"]').trigger('click');await flushPromises(); }

describe('manual plans page',()=>{
 it('loads owned plans and clearly labels unverified intent and far-date policy',async()=>{const {wrapper}=await mountView();expect(wrapper.text()).toContain('人工意向场馆');expect(wrapper.text()).toContain('尚未核验');await edit(wrapper);expect(wrapper.text()).toContain('当前不可查询');expect(wrapper.text()).toContain('07:30');expect(wrapper.text()).toContain('估计');expect(wrapper.text()).not.toContain('立即预约');});
 it('creates a semantic draft with time priority and exact price',async()=>{const {wrapper,api}=await mountView(apiFixture({list:vi.fn(async()=>({plans:[]}))}));expect(wrapper.text()).toContain('还没有预约计划');await newDraft(wrapper);await wrapper.get('[data-testid="add-time"]').trigger('click');await wrapper.get('[name="start_time_1"]').setValue('20:00');await wrapper.get('[data-testid="time-up-1"]').trigger('click');await wrapper.get('[name="price_ceiling"]').setValue('0.29');await wrapper.get('form').trigger('submit');await flushPromises();expect(api.create.mock.calls[0][0]).toMatchObject({venue_preference:'周末人工意向',court_preferences:['6号场','5号场'],preferred_start_times:['20:00','18:00'],price_ceiling_minor:29});expect(wrapper.text()).toContain('已保存');expect(wrapper.text()).toContain('周末人工意向');});
 it('edits using base_version and opens immutable history',async()=>{const {wrapper,api}=await mountView();await edit(wrapper);await wrapper.get('[name="venue_preference"]').setValue('修改意向');await wrapper.get('form').trigger('submit');await flushPromises();expect(api.update.mock.calls[0].slice(0,2)).toEqual(['synthetic-plan',1]);expect(wrapper.text()).toContain('版本 2');await wrapper.get('[data-testid="history-plan"]').trigger('click');await flushPromises();expect(wrapper.text()).toContain('版本历史');expect(wrapper.findAll('details').length).toBeGreaterThanOrEqual(2);expect(wrapper.text()).toContain('人工意向场馆');});
 it('keeps draft on 409, previews latest separately and replaces only on explicit adoption',async()=>{const {wrapper}=await mountView(apiFixture({update:vi.fn(async()=>{throw {status:409,code:'plan_version_conflict'};})}));await edit(wrapper);await wrapper.get('[name="venue_preference"]').setValue('我的未保存意向');await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('版本冲突');expect(wrapper.get('[name="venue_preference"]').element.value).toBe('我的未保存意向');await wrapper.get('[data-testid="view-latest"]').trigger('click');await flushPromises();expect(wrapper.text()).toContain('另一个窗口保存');expect(wrapper.get('[name="venue_preference"]').element.value).toBe('我的未保存意向');await wrapper.get('[data-testid="adopt-latest"]').trigger('click');await flushPromises();expect(wrapper.get('[name="venue_preference"]').element.value).toBe('另一个窗口保存');});
 it('does not report load failure as an empty list and retries successfully',async()=>{let bad=true;const {wrapper}=await mountView(apiFixture({list:vi.fn(async()=>{if(bad)throw {kind:'network'};return {plans:[]};})}));expect(wrapper.text()).toContain('计划读取失败');expect(wrapper.text()).not.toContain('还没有预约计划');bad=false;await wrapper.get('[data-testid="refresh-plans"]').trigger('click');await flushPromises();expect(wrapper.text()).toContain('还没有预约计划');});
 it('preserves form after network save failure and shows uncertain outcome',async()=>{const {wrapper}=await mountView(apiFixture({update:vi.fn(async()=>{throw {kind:'network'};})}));await edit(wrapper);await wrapper.get('[name="venue_preference"]').setValue('保留文本');await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.get('[name="venue_preference"]').element.value).toBe('保留文本');expect(wrapper.text()).toContain('保存结果尚未确认');});
 it('shows field errors without discarding input',async()=>{const {wrapper}=await mountView(apiFixture({update:vi.fn(async()=>{throw {code:'invalid_plan',status:400,fields:{venue_preference:'场馆文本无效'}};})}));await edit(wrapper);await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('场馆文本无效');expect(wrapper.get('[name="venue_preference"]').attributes('aria-invalid')).toBe('true');});
 it('blocks duplicates while saving and disables editing actions',async()=>{let resolve;const {wrapper,api}=await mountView(apiFixture({update:vi.fn(()=>new Promise(r=>{resolve=r;}))}));await edit(wrapper);await wrapper.get('form').trigger('submit');await wrapper.get('form').trigger('submit');expect(api.update).toHaveBeenCalledOnce();expect(wrapper.get('[data-testid="new-plan"]').element.disabled).toBe(true);resolve({plan:plan(2)});await flushPromises();});
 it('clears form and ignores late data after losing Session then logging back into the same user',async()=>{let resolve;const {wrapper,session}=await mountView(apiFixture({update:vi.fn(()=>new Promise(r=>{resolve=r;}))}));await edit(wrapper);await wrapper.get('form').trigger('submit');session.user=null;session.status='unauthenticated';await flushPromises();expect(wrapper.find('form').exists()).toBe(false);session.user={user_id:'a',username:'Alice'};session.status='authenticated';await flushPromises();resolve({plan:plan(2,{venue_preference:'迟到结果'})});await flushPromises();expect(wrapper.text()).not.toContain('迟到结果');expect(wrapper.find('form').exists()).toBe(false);});
 it('clears owned data on account switch and ignores the old list response',async()=>{let resolve;let calls=0;const {wrapper,session}=await mountView(apiFixture({list:vi.fn(()=>++calls===1?new Promise(r=>{resolve=r;}):Promise.resolve({plans:[]}))}));session.user={user_id:'b',username:'Bob'};await flushPromises();resolve({plans:[plan()]});await flushPromises();expect(wrapper.text()).not.toContain('人工意向场馆');expect(wrapper.text()).toContain('还没有预约计划');});
 it('clears owned data when the same user receives a new session token',async()=>{const {wrapper,session}=await mountView();await edit(wrapper);session.csrfToken='csrf-rotated';await flushPromises();expect(wrapper.find('form').exists()).toBe(false);expect(wrapper.text()).not.toContain('编辑预约意向');});
 it('uses stored currency/timezone for edits and does not accept absent currency price',async()=>{const {wrapper}=await mountView(apiFixture({options:vi.fn(async()=>({catalog_status:'not_configured',venues:[],context:{...context,currency_code:null,currency_minor_unit_exponent:null,timezone_name:'UTC'}}))}));await edit(wrapper);expect(wrapper.get('[name="price_ceiling"]').element.value).toBe('12.34');expect(wrapper.text()).toContain('CNY');expect(wrapper.text()).toContain('Asia/Shanghai');await newDraft(wrapper);expect(wrapper.find('[name="price_ceiling"]').exists()).toBe(false);expect(wrapper.text()).toContain('未配置货币');});
});
